---
# tasks file for ansible-role-filebot

# -------------
# Include variables
# -------------
- name: Get most specific FileBot variables available
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_system }}.yml"  

# -------------
# Verify installed
# -------------  
- include: setup-deb.yml
  sudo: Yes
  when:  ansible_pkg_mgr == 'apt'

- include: setup-MacOSX.yml
  sudo: Yes
  when: ansible_distribution == 'MacOSX'
