---
# tasks file for ansible-role-filebot

# ----- SETUP -----
- include: setup-deb.yml
  sudo: Yes
  when:  ansible_pkg_mgr == 'apt'


- include: setup-cask.yml
  sudo: Yes
  when: ansible_distribution == 'MacOSX'

