---
# tasks file for ansible-role-filebot

# -------------
# Include variables
# -------------
- name: Get most specific FileBot variables available
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_system }}.yml"  

# -------------
# Verify installed
# -------------  
- include: setup-deb.yml
  sudo: Yes
  when:  filebot_pkg_install_using == 'Debian_dpkg'

- include: setup-MacOSX.yml
  sudo: Yes
  when: filebot_pkg_install_using == 'MacOSX_homebrew'
