---
# tasks file for ansible-role-filebot


- include: setup-deb.yml
  become: Yes
  when:  ansible_pkg_mgr == 'apt'


- include: setup-cask.yml
  become: Yes
  when: ansible_distribution == 'MacOSX'


- name: "ensure templated filebot.amc.sh"
  template: src="filebot.amc.sh.j2" dest="{{ filebot_amc_path }}" mode=0755


...