---
# Debian (Linux) tasks file for ansible-role-filebot

- name: Debian | check for installation 
  stat: path="{{ filebot_dir_install }}/filebot"
  register: filebot_bin

- name: Debian | ensure download dir can read, write, execute
  file:
    path: "{{ filebot_dir_download }}"
    state: directory
    mode: "u+rwx"
    owner: "{{ ansible_ssh_user }}"
  when: not filebot_bin.stat.exists

- name: Debian | download installer
  get_url:
    url: "{{ filebot_pkg_url[ansible_architecture] }}"
    dest: "{{ filebot_dir_download }}/filebot.deb"
  when: not filebot_bin.stat.exists
  
- name: Debian | run the installer
  sudo: Yes
  apt:
    deb: "{{ filebot_dir_download }}/filebot.deb"
  when: not filebot_bin.stat.exists
    